# Generated by Django 3.2.8 on 2022-03-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPizza',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pizzas.pizzamodel_toppings',),
        ),
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'verbose_name': 'My pizza recipes', 'verbose_name_plural': 'Pizza recipes'},
        ),
        migrations.AlterModelOptions(
            name='toppingsmodel',
            options={'verbose_name': 'Toppings', 'verbose_name_plural': 'Toppings'},
        ),
    ]
