# Generated by Django 3.2.8 on 2022-03-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220311_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='delivery_club',
            new_name='delivery_status',
        ),
    ]
